### ISSUE TITLE
Plans for 0.9 

### ISSUE THREAD

**Issue by minghuaw** [minghuaw/fe2o3-amqp#215]
## Update dependencies

The following dependencies of `fe2o3-amqp` have new versions that could be treated as "breaking" changes.

- `tokio-rustls` has released "0.25"
- `rustls` has released "0.22"
- `webpki-roots` has released "0.26"

These updates are breaking because `Connection` can be built with custom `TlsConnector`.

There are some other dependencies for subcrates (eg. `serde_amqp`) that should be considered breaking.

`serde_amqp` dependencies

- `ordered-float` has released "4.0"
- `indexmap` has released "2.0"

`fe2o3-amqp-types`

- `ordered-float` has released "4.0"

`fe2o3-amqp-ws` dependencies

- `http` has released "1.0"
- `tungstenite` has released "0.21"
- `tokio-tungstenite` has released "0.21"

## Unify versioning

It's becoming a little hard to keep track of difference versions of the subcrates. Since updating the dependency would introduce breaking change to almost all subcrates, this would be a nice time to unify the minor version number, so all crates will be released with a version number of "0.9" this time.

## TODO

- [ ] Update dependencies for `serde_amqp` and `fe2o3-amqp-types`
- [ ] Update dependencies for `fe2o3-amqp-ws`
- [ ] Update dependencies for `fe2o3-amqp`
- [ ] Unify version number
- [ ] Review other issues that could be addressed together?
